name = "my-app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
node_version = "20"
[build.environment]
NODE_VERSION = "20"

[site]
bucket = ".next/static"
entry-point = "."